### ISSUE TITLE
Build in Docker container.

### ISSUE THREAD

**Issue by thewtex** [OpenChemistry/tomviz-superbuild#78]
I am trying to get this to build in a Docker container:

  https://hub.docker.com/r/thewtex/centos-build/

This will given developers a instance development environment on Linux, and it will allow CI testing on GitHub.

Currently I am encountering build errors.

@mathturtle Marcus said you did some work in this area? 

CC: @cryos

**Comment by mathturtle** [comment]
@thewtex:

Since tomviz requires C++11, I seriously doubt the compilers on your CentOS5 build instance are new enough to build it unless you built them yourself first.

I have a (admittedly basic) docker instance that I use with buildbot to create linux builds of tomviz.  I'll send you the Dockerfile via email.  I based it on Debian 7, which was the oldest debian version I could find where I didn't have to build my own compilers.  I used Debian since ParaView uses Debian VMs to build its linux binaries.  See [here](https://buildbot.kitware.com/grid?width=12&category=tomviz-experimental) for the build results.  You can even download and try out the Linux binaries from CDash if you want, but I'm not 100% sure they work.  They contain all the required libraries but I was having some errors running them that I didn't understand.

Without more specifics on the build errors, I can't really say much more.

**Comment by thewtex** [comment]
@mathturtle cool!

The Docker image referenced above has a backported compiler that supports C++11 (GCC 4.8.2).

I am getting a numpy and qt build errors.  Looking into it...

**Comment by mathturtle** [comment]
Qt: I can't really help that much.  You need a list of packages including some X stuff installed, but I don't think the list from Debian will be much help on CentOS (you have my list in the docker image).  Also, you may want to make sure you can build Qt5 since we will be switching to that in the near future.  I know ParaView had to update from Debian 4 to Debian 6 when they looked at switching their builds to use Qt5.

numpy: Probably to do with the LD_LIBRARY_PATH and/or PYTHONPATH?  You'll need a fortran compiler for numpy/scipy.  I thought I finally had those sorted out for Linux.  scipy is even more "fun" to build when you get that far...

Pre-emptively: you may also have trouble with my ITK binaries since I built them on Debian7 and I'm pretty sure that is newer than CentOS5.

**Comment by thewtex** [comment]
Thanks for the tips.

I nuked the build directory and restarted again. NumPy has been completing. It looks like a couple of work arounds were required for Qt / Qt's build system.  It is still building..

**Comment by thewtex** [comment]
Pull request #80 addresses the Qt build issue (Qt does not always pick up the right linker with a non-system toolchain).

Also, there is the Python patch, which I think addressed the NumPy issue.

I started on a Docker image file here:

  https://github.com/thewtex/tomviz-docker

This repository could be transferred to OpenChemistry.

This image is a good start, but I still get a build error.

```
[ 22%] Building CXX object VTK/Rendering/OpenGL2/CMakeFiles/vtkRenderingOpenGL2.dir/vtkXOpenGLRenderDevice.cxx.o
/usr/src/tomviz-superbuild-build/paraview/src/paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderDevice.cxx: In member function ‘virtual bool vtkXOpenGLRenderDevice::CreateNewWindow(const vtkRecti&, const string&)’:
/usr/src/tomviz-superbuild-build/paraview/src/paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderDevice.cxx:256:75: error: ‘glXGetProcAddressARB’ was not declared in this scope
         glXGetProcAddressARB((const GLubyte *)"glXCreateContextAttribsARB");
                                                                           ^
/usr/src/tomviz-superbuild-build/paraview/src/paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderDevice.cxx:281:7: error: ‘GLX_CONTEXT_MAJOR_VERSION_ARB’ was not declared in this scope
       GLX_CONTEXT_MAJOR_VERSION_ARB, 4,
       ^
/usr/src/tomviz-superbuild-build/paraview/src/paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderDevice.cxx:282:7: error: ‘GLX_CONTEXT_MINOR_VERSION_ARB’ was not declared in this scope
       GLX_CONTEXT_MINOR_VERSION_ARB, 4,
       ^
gmake[5]: *** [VTK/Rendering/OpenGL2/CMakeFiles/vtkRenderingOpenGL2.dir/vtkXOpenGLRenderDevice.cxx.o] Error 1
gmake[4]: *** [VTK/Rendering/OpenGL2/CMakeFiles/vtkRenderingOpenGL2.dir/all] Error 2
gmake[3]: *** [all] Error 2
CMake Error at /usr/src/tomviz-superbuild-build/pv-paraview-build.cmake:27 (message):
  Failed!!!


make[2]: *** [paraview/src/paraview-stamp/paraview-build] Error 1
make[1]: *** [CMakeFiles/paraview.dir/all] Error 2
```

Even though *GL/glx.h* is available in the container, and the function it is complaining about is declared there, this error still comes up.

Looking through VTK, there is some fanciness going on surrounding this function in the OpenGL backend:

https://github.com/Kitware/VTK/blob/4f434639bf5b40e5d2b55c0cfd0337c8d8a84811/Rendering/OpenGL/CMakeLists.txt#L193-L228

Maybe this needs to be ported to OpenGL2? I won't have time to dive in for a little while if you want to take it on.

To reproduce the build, build the referenced Docker image, then start it with:

```
docker run -it --name tomviz -v ~/src/tomviz-superbuild/:/usr/src/tomviz-superbuild -v ~/bin/tomviz-superbuild-build/:/usr/src/tomviz-superbuild-build tomviz/tomviz-build bash
```
where `~/src/tomviz-superbuild` has a checkout of the *docker* branch and `~/bin/tomviz-superbuild-build` is a clean build directory.

Start the build by running:
```
cmake -Dqt4_WORK_AROUND_BROKEN_ASSISTANT_BUILD=1 -DENABLE_fftw3double=1 -DENABLE_fftw3float=1 -DENABLE_lapack=1 -DENABLE_numpy=1 -DENABLE_pyfftw=1 -DENABLE_scipy=1 -DENABLE_tbb=1 -DENABLE_tomviz=1 -DCMAKE_BUILD_TYPE=MinSizeRel ../tomviz-superbuild && make -j6
```

**Comment by mathturtle** [comment]
@thewtex Cool!  I'll try out the new Docker image later and see what I can find about the glx error.

Have you tested building Qt5 in your docker image yet?  We plan to switch tomviz to use it in the next few weeks and it requires newer dependencies than Qt4, which may not be available in your docker image.  I'll try that out too.

**Comment by mathturtle** [comment]
I just tried a Qt5 build in your docker image just to see what would happen.  I got this after a few minutes using as close as I could to the configuration from @cryos's qt5-porting branch (#76).
```
/root/qt5/qt5-src/qtbase/src/platformsupport/fbconvenience/qfbvthandler.cpp:46:26: fatal error: sys/signalfd.h: No such file or directory
 #include <sys/signalfd.h>
                          ^
```

**Comment by thewtex** [comment]
@mathturtle great, thanks!

I did not try qt5. Googling around a bit, it seems *signalfd* is not available for this older glibc.  Maybe it can be avoided with a configure flag?

**Comment by cryos** [comment]
@mathturtle this seems to be largely resolved now, please close this issue if you agree.

**Comment by mathturtle** [comment]
Yes, I think this is resolved now.  The Dockerfile for the container we use for our builds is currently in the buildbot scripts repository if you want to look at it.  And I just tested the new binaries and they were working for me.

**Comment by jcfr** [comment]
```
[ 22%] Building CXX object VTK/Rendering/OpenGL2/CMakeFiles/vtkRenderingOpenGL2.dir/vtkXOpenGLRenderDevice.cxx.o
/usr/src/tomviz-superbuild-build/paraview/src/paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderDevice.cxx: In member function ‘virtual bool vtkXOpenGLRenderDevice::CreateNewWindow(const vtkRecti&, const string&)’:
/usr/src/tomviz-superbuild-build/paraview/src/paraview/VTK/Rendering/OpenGL2/vtkXOpenGLRenderDevice.cxx:256:75: error: ‘glXGetProcAddressARB’ was not declared in this scope
         glXGetProcAddressARB((const GLubyte *)"glXCreateContextAttribsARB");
                                                                           ^
```

If anyone ends on this page after a good search, the following Pr should address the issue reported above.
See https://gitlab.kitware.com/vtk/vtk/merge_requests/2759

It should be integrated in VTK soon.
